import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Duty Timer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Duty Timer
        </h1>

        <Link href="/register">
            <a className="ml-4 text-sm text-gray-700 underline">
                Register
            </a>
        </Link>
      </main>
    </div>
  )
}

export default Home
